var wid = 12.3, len = 52.6, heig = 89.9, a = 28.3;
console.log("Area of square");
var square = a * a;
var sq = square.toFixed(2);
console.log(sq);
console.log("Area of rectangle");
var rec = wid * heig;
var rt = rec.toFixed(2);
console.log(rt);
console.log("Area of triangle");
var tri = wid * heig / 2;
var tr = tri.toFixed(2);
console.log(tr);
